# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1091, 709)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(1091, 709))
        Dialog.setMaximumSize(QtCore.QSize(1091, 709))
        Dialog.setStyleSheet("")
        self.widget_3 = QtWidgets.QWidget(Dialog)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 611, 711))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(751, 711))
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(70, 210, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(70, 270, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 652, 35, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setGeometry(QtCore.QRect(610, 0, 481, 711))
        self.widget_2.setMinimumSize(QtCore.QSize(421, 651))
        self.widget_2.setMaximumSize(QtCore.QSize(10000, 10000))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.widget_2.setObjectName("widget_2")
        self.login_input = QtWidgets.QLineEdit(self.widget_2)
        self.login_input.setGeometry(QtCore.QRect(100, 240, 281, 31))
        self.login_input.setStyleSheet("border: 1px;\n"
"border-color: rgb(7, 71, 166);\n"
"border-style: outset;\n"
"border-radius: 3px;")
        self.login_input.setText("")
        self.login_input.setObjectName("login_input")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(100, 210, 111, 31))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"color: rgb(7, 71, 166);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(100, 290, 111, 31))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"color:  rgb(7, 71, 166);")
        self.label_4.setObjectName("label_4")
        self.login_button = QtWidgets.QPushButton(self.widget_2)
        self.login_button.setGeometry(QtCore.QRect(160, 430, 161, 31))
        self.login_button.setStyleSheet("background-color:  rgb(7, 71, 166);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 2px;")
        self.login_button.setObjectName("login_button")
        self.create_acc_button = QtWidgets.QPushButton(self.widget_2)
        self.create_acc_button.setGeometry(QtCore.QRect(160, 460, 161, 31))
        self.create_acc_button.setStyleSheet("")
        self.create_acc_button.setFlat(True)
        self.create_acc_button.setObjectName("create_acc_button")
        self.pass_input = QtWidgets.QLineEdit(self.widget_2)
        self.pass_input.setGeometry(QtCore.QRect(100, 320, 281, 31))
        self.pass_input.setStyleSheet("border: 1px;\n"
"border-color: rgb(7, 71, 166);\n"
"border-style: outset;\n"
"border-radius: 3px;")
        self.pass_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_input.setObjectName("pass_input")
        self.create_acc_button_2 = QtWidgets.QPushButton(self.widget_2)
        self.create_acc_button_2.setGeometry(QtCore.QRect(100, 360, 101, 21))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.create_acc_button_2.setFont(font)
        self.create_acc_button_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.create_acc_button_2.setObjectName("create_acc_button_2")
        self.create_acc_button.raise_()
        self.login_input.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.login_button.raise_()
        self.pass_input.raise_()
        self.create_acc_button_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Just On Time"))
        self.label_2.setText(_translate("Dialog", "Welcome to timezone"))
        self.pushButton_3.setText(_translate("Dialog", "RU"))
        self.label_3.setText(_translate("Dialog", "Логин"))
        self.label_4.setText(_translate("Dialog", "Пароль"))
        self.login_button.setText(_translate("Dialog", "Войти"))
        self.create_acc_button.setText(_translate("Dialog", "Создать аккаунт"))
        self.create_acc_button_2.setText(_translate("Dialog", "Забыли пароль?"))
